# 端口和数据库配置在 application-prod.yml / application-test.yml 中按环境区分

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: org.example.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
