name: Deploy Java Backend


on:
  push:
    branches:
      - main

  workflow_dispatch:



jobs:

  deploy:

    runs-on: ubuntu-latest


    steps:


      # 拉取代码
      - name: Checkout code
        uses: actions/checkout@v5



      # 配置JDK
      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'



      # Maven打包
      - name: Build jar
        run: |
          mvn clean package -DskipTests



      # 查看并固定jar名称
      - name: Prepare jar
        run: |

          echo "====== 查看target ======"

          ls -lh target


          echo "====== 查找jar ======"

          find target -name "*.jar"


          echo "====== 复制jar ======"

          cp target/*.jar app.jar


          echo "====== 最终文件 ======"

          ls -lh app.jar





      # 上传服务器
      - name: Upload jar
        uses: appleboy/scp-action@v0.1.7

        with:

          host: ${{ secrets.SERVER_HOST }}

          username: root

          password: ${{ secrets.SERVER_PASSWORD }}


          source: "app.jar"

          target: "/www/wwwroot/java/"





      # 检查服务器文件
      - name: Check server file

        uses: appleboy/ssh-action@v1

        with:

          host: ${{ secrets.SERVER_HOST }}

          username: root

          password: ${{ secrets.SERVER_PASSWORD }}



          script: |

            echo "======服务器文件======"

            cd /www/wwwroot/java

            ls -lh





      # 重启Java
      - name: Restart Java

        uses: appleboy/ssh-action@v1


        with:


          host: ${{ secrets.SERVER_HOST }}

          username: root

          password: ${{ secrets.SERVER_PASSWORD }}



          timeout: 60s

          command_timeout: 2m



          script: |


            cd /www/wwwroot/java



            echo "======停止旧服务======"



            PID=$(ps -ef | grep app.jar | grep -v grep | awk '{print $2}')



            if [ -n "$PID" ]; then

              kill $PID

              echo "停止旧服务 PID=$PID"

              sleep 3

            else

              echo "没有旧服务"

            fi





            echo "======启动Java======"



            nohup java -jar app.jar > java.log 2>&1 &



            echo "等待启动..."

            sleep 10




            echo "======检查Java======"



            NEW_PID=$(ps -ef | grep app.jar | grep -v grep | awk '{print $2}')



            if [ -n "$NEW_PID" ]; then


              echo "=============================="

              echo "🎉 Java启动成功"

              echo "PID: $NEW_PID"

              echo "文件: app.jar"

              echo "日志: /www/wwwroot/java/java.log"

              echo "=============================="



            else



              echo "=============================="

              echo "❌ Java启动失败"

              echo "日志如下："

              cat java.log

              echo "=============================="



              exit 1


            fi





      # GitHub显示成功
      - name: Deploy Success

        run: |

          echo "=============================="

          echo "🎉 Java 后端部署成功"

          echo "服务器: ${{ secrets.SERVER_HOST }}"

          echo "时间: $(date)"

          echo "=============================="
